// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfM83eWykv5JoFxB96O4xG2ROejM2Ptzg',
    appId: '1:569109690273:web:84af1b87b80d97fc78bde0',
    messagingSenderId: '569109690273',
    projectId: 'memonnotify',
    authDomain: 'memonnotify.firebaseapp.com',
    storageBucket: 'memonnotify.firebasestorage.app',
    measurementId: 'G-C4B88J4SM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzRFILAsY29JNi8MhyNDgfRzwYZMrtJA',
    appId: '1:569109690273:android:f190bcc7ce48f9b478bde0',
    messagingSenderId: '569109690273',
    projectId: 'memonnotify',
    storageBucket: 'memonnotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkaNZv4Qihkenv-nYIrTK96QvNiq-60p4',
    appId: '1:569109690273:ios:64644495a52bc5e878bde0',
    messagingSenderId: '569109690273',
    projectId: 'memonnotify',
    storageBucket: 'memonnotify.firebasestorage.app',
    iosBundleId: 'com.example.memonNotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkaNZv4Qihkenv-nYIrTK96QvNiq-60p4',
    appId: '1:569109690273:ios:64644495a52bc5e878bde0',
    messagingSenderId: '569109690273',
    projectId: 'memonnotify',
    storageBucket: 'memonnotify.firebasestorage.app',
    iosBundleId: 'com.example.memonNotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfM83eWykv5JoFxB96O4xG2ROejM2Ptzg',
    appId: '1:569109690273:web:498f988a875da26178bde0',
    messagingSenderId: '569109690273',
    projectId: 'memonnotify',
    authDomain: 'memonnotify.firebaseapp.com',
    storageBucket: 'memonnotify.firebasestorage.app',
    measurementId: 'G-3SRT995MD9',
  );
}
